# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('slug', models.SlugField(verbose_name='Cz\u0119\u015b\u0107 adresu')),
                ('limit', models.PositiveIntegerField(default=5, verbose_name='Ilo\u015b\u0107 wy\u015bwietlanych element\xf3w')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Rotator',
                'verbose_name_plural': 'Rotatory',
            },
        ),
        migrations.CreateModel(
            name='HeroEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytu\u0142')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Podtytu\u0142')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lead')),
                ('url', models.CharField(max_length=200, verbose_name='URL do kt\xf3rego prowadzi')),
                ('button_text', models.CharField(blank=True, default=b'Zobacz odcinek', max_length=255, null=True, verbose_name='Przycisk dalej')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'heros', verbose_name='Ilustracja')),
                ('sort', models.IntegerField(default=100, verbose_name='Kolejno\u015b\u0107')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy jest aktywny')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heros.Hero')),
            ],
            options={
                'ordering': ['sort', '-added', 'title'],
                'verbose_name': 'Wpis w rotatorze',
                'verbose_name_plural': 'Wpisy w rotatorach',
            },
        ),
    ]
