# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroentry',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='heros.Hero'),
        ),
    ]
