# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0002_auto_20170827_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroentry',
            name='image',
            field=models.ImageField(default='static/hero_default.png', upload_to=b'heros', verbose_name='Ilustracja'),
            preserve_default=False,
        ),
    ]
