# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0004_heroentry_publish_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroentry',
            options={'ordering': ['sort', '-modified', 'title'], 'verbose_name': 'Wpis w rotatorze', 'verbose_name_plural': 'Wpisy w rotatorach'},
        ),
    ]
