# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0005_auto_20171101_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroentry',
            name='on_slider',
            field=models.BooleanField(default=False, verbose_name='Put on slider'),
        ),
    ]
