# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-22 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0005_auto_20171101_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['name'], 'verbose_name': 'Hero', 'verbose_name_plural': 'Heros'},
        ),
        migrations.AlterModelOptions(
            name='heroentry',
            options={'ordering': ['sort', '-publish_time', '-added', '-modified', 'title'], 'verbose_name': 'Hero entry', 'verbose_name_plural': 'Hero entries'},
        ),
    ]
