# Generated by Django 2.2 on 2020-06-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0006_auto_20180422_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroentry',
            name='button_text',
            field=models.CharField(blank=True, default='Zobacz odcinek', max_length=255, null=True, verbose_name='Przycisk dalej'),
        ),
        migrations.AlterField(
            model_name='heroentry',
            name='image',
            field=models.ImageField(upload_to='heros', verbose_name='Ilustracja'),
        ),
    ]
