# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170827_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to=b'blog-images', verbose_name='Obraz w\u0105ski/p\u0142ywaj\u0105cy'),
        ),
    ]
