# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-01 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170918_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image_float',
        ),
    ]
