# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-12 19:30
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_entry_image_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Tresc'),
        ),
    ]
