# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20180503_2232'),
        ('blog', '0006_auto_20171112_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.MediaPatronage'),
        ),
    ]
