# Generated by Django 2.2 on 2020-06-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180605_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog-images', verbose_name='Obraz szeroki (cover)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='blog-images', verbose_name='Obraz wąski/pływający'),
        ),
    ]
