# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20170916_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nazwa programu'),
        ),
    ]
