# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-12 19:54
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20170918_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='program',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Opis'),
        ),
    ]
