# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20171112_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
