# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models
from ..utils import get_slug


def prepopulate_slugs(apps, schema_editor):
    Episode = apps.get_model('program', 'Episode')

    for episode in Episode.objects.all():
        episode.slug = get_slug(Episode, episode.title)
        episode.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_episode_slug'),
    ]

    operations = [
        migrations.RunPython(prepopulate_slugs, migrations.RunPython.noop),
    ]
