# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_slug_prepopulate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
