# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tagging.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_slug_prepopulate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set([]),
        ),
    ]
