# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.deletion
import tagging.fields
import tinymce.models

class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_auto_20180603_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('new_tags', tagging.fields.TagField(blank=True, max_length=255, null=True, verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='playlistepisode',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_episodes',
                                    to='program.Episode'),
        ),
        migrations.AddField(
            model_name='playlistepisode',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_episodes',
                                    to='program.Playlist'),
        ),
        migrations.AddField(
            model_name='episode',
            name='playlist',
            field=models.ManyToManyField(related_name='episodes', through='program.PlaylistEpisode',
                                         to='program.Playlist'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numer odcinka'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Program'),
        ),
    ]
