# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20180602_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numer odcinka'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set([]),
        ),
    ]
