# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20180603_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('episode', models.ForeignKey(on_delete=f, related_name='playlist_episodes', to='program.Episode')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Playlist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
