# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20180602_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Episode')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Playlist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='playlist',
            field=models.ManyToManyField(through='program.PlaylistEpisode', to='program.Playlist'),
        ),
    ]
