# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20180603_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='playlist',
            field=models.ManyToManyField(related_name='episodes', through='program.PlaylistEpisode', to='program.Playlist'),
        ),
    ]
