# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_playlistepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistepisode',
            name='episode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_episodes', to='program.Episode'),
            preserve_default=False,
        ),
    ]
