# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-03 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20180603_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='playlist',
            field=models.ManyToManyField(related_name='episodes', through='program.PlaylistEpisode', to='program.Playlist'),
        ),
        migrations.AddField(
            model_name='playlistepisode',
            name='episode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_episodes', to='program.Episode'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='playlistepisode',
            unique_together=set([('episode', 'playlist', 'position')]),
        ),
    ]
