# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20180603_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='playlist',
            field=models.ManyToManyField(related_name='episodes', through='program.PlaylistEpisode', to='program.Playlist'),
        ),
    ]
