# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20180503_2232'),
        ('program', '0011_auto_20180603_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='related_events',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlists', to='partners.MediaPatronage'),
        ),
    ]
