# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-02 22:20
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20180603_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='new_tags',
            field=tagging.fields.TagField(blank=True, max_length=255, null=True, verbose_name='Tags'),
        ),
    ]
