# Generated by Django 2.2 on 2020-06-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_playlist_related_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(upload_to='episodes', verbose_name='Ilustracja'),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hosts', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='related_events',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='partners.MediaPatronage'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, upload_to='programs', verbose_name='Obraz dla programu'),
        ),
    ]
