# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rotv_apps.shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Original URL')),
                ('short_slug', models.SlugField(default=rotv_apps.shortener.models.get_short_hash, unique=True, verbose_name='Short URL slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expires')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shortened_urls', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_shortened_urls', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'ordering': ['-modified', '-created'],
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
            },
        ),
    ]
