# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='short_slug',
            new_name='slug',
        ),
    ]
