# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('slug', models.SlugField(verbose_name='Identyfikator slug')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'nav', verbose_name='Obraz w nawigacji')),
                ('order', models.IntegerField(default=100, verbose_name='Kolejno\u015b\u0107')),
                ('subnav_type', models.PositiveIntegerField(blank=True, choices=[[1, b'Normalne'], [2, b'Z ilustracjami']], null=True, verbose_name='Typ podmenu')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='navigations.Nav')),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name': 'Element nawigacji klasycznej',
                'verbose_name_plural': 'Elementy nawigacji klasycznej',
            },
        ),
    ]
