# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subnav', to='navigations.Nav'),
        ),
    ]
