# Generated by Django 2.2 on 2020-06-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigations', '0002_auto_20170827_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nav', verbose_name='Obraz w nawigacji'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='subnav_type',
            field=models.PositiveIntegerField(blank=True, choices=[[1, 'Normalne'], [2, 'Z ilustracjami']], null=True, verbose_name='Typ podmenu'),
        ),
    ]
