# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa w\u0142asna')),
                ('logo', models.ImageField(upload_to=b'logos/colaborator', verbose_name='Logotyp')),
                ('url', models.URLField(blank=True, verbose_name='Adres url')),
                ('active', models.BooleanField(default=False, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Wsp\xf3\u0142pracuj\u0105cy',
                'verbose_name_plural': 'Wsp\xf3\u0142pracuj\u0105cy',
            },
        ),
        migrations.CreateModel(
            name='MediaPatron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa w\u0142asna')),
                ('logo', models.ImageField(upload_to=b'logos/patron', verbose_name='Logotyp')),
                ('url', models.URLField(blank=True, verbose_name='Adres url')),
                ('active', models.BooleanField(default=False, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Patron',
                'verbose_name_plural': 'Patroni',
            },
        ),
        migrations.CreateModel(
            name='MediaPatronage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa w\u0142asna')),
                ('logo', models.ImageField(upload_to=b'logos/patronage', verbose_name='Logotyp')),
                ('url', models.URLField(blank=True, verbose_name='Adres url')),
                ('active', models.BooleanField(default=False, verbose_name='Aktywny')),
                ('start', models.DateField(verbose_name='Start wydarzenia')),
                ('end', models.DateField(verbose_name='Koniec wydarzenia')),
            ],
            options={
                'verbose_name': 'Patronat wydarzenia',
                'verbose_name_plural': 'Patronaty wydarze\u0144',
            },
        ),
        migrations.CreateModel(
            name='NormalMediaPatronage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa w\u0142asna')),
                ('logo', models.ImageField(upload_to=b'logos/patronage', verbose_name='Logotyp')),
                ('url', models.URLField(blank=True, verbose_name='Adres url')),
                ('active', models.BooleanField(default=False, verbose_name='Aktywny')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Od kiedy wy\u015bwietla\u0107')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Do kiedy wy\u015bwietla\u0107')),
            ],
            options={
                'verbose_name': 'Patronat produktu',
                'verbose_name_plural': 'Patronaty produkt\xf3w',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa w\u0142asna')),
                ('logo', models.ImageField(upload_to=b'logos/partner', verbose_name='Logotyp')),
                ('url', models.URLField(blank=True, verbose_name='Adres url')),
                ('active', models.BooleanField(default=False, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partnerzy',
            },
        ),
    ]
