# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapatronage',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Opis wydarzenia, charakter, grupa docelowa i inne.', verbose_name='Informacje dodatkowe'),
        ),
        migrations.AddField(
            model_name='mediapatronage',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Maksymalna szeroko\u015b\u0107 800px', null=True, upload_to=b'uploads/partners/banners', verbose_name='Banner wydarzenia'),
        ),
        migrations.AddField(
            model_name='mediapatronage',
            name='city',
            field=models.CharField(default='', max_length=128, verbose_name='Miasto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediapatronage',
            name='contact_email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail kontaktowy organizatora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediapatronage',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Sugerowana szeroko\u015b\u0107 mi\u0119dzy 1000px - 1600px', null=True, upload_to=b'uploads/partners/covers', verbose_name='Szeroki obraz typu cover'),
        ),
        migrations.AddField(
            model_name='mediapatronage',
            name='small_image',
            field=models.ImageField(blank=True, help_text='Szeroko\u015b\u0107do 300px', null=True, upload_to=b'uploads/partners/images', verbose_name='Ma\u0142y obrazk'),
        ),
        migrations.AddField(
            model_name='mediapatronage',
            name='spot',
            field=models.CharField(blank=True, help_text='Dok\u0142adna nazwa szko\u0142y, targ\xf3w, lokacji', max_length=255, verbose_name='Miejsce wydarzenia'),
        ),
        migrations.AlterField(
            model_name='mediapatronage',
            name='end',
            field=models.DateField(verbose_name='Data zako\u0144czenia'),
        ),
        migrations.AlterField(
            model_name='mediapatronage',
            name='logo',
            field=models.ImageField(upload_to=b'logos/patronage', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='mediapatronage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa wydarzenia'),
        ),
        migrations.AlterField(
            model_name='mediapatronage',
            name='start',
            field=models.DateField(verbose_name='Data pocz\u0105tku'),
        ),
        migrations.AlterField(
            model_name='mediapatronage',
            name='url',
            field=models.URLField(blank=True, verbose_name='Adres url strony internetowej'),
        ),
    ]
