# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-25 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20171121_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediapatronage',
            options={'verbose_name': 'Wydarzenie', 'verbose_name_plural': 'Wydarzenia'},
        ),
        migrations.AlterField(
            model_name='mediapatronage',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Aktywny patronat?'),
        ),
        migrations.AlterField(
            model_name='mediapatronage',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Szeroko\u015b\u0107 sugerowana: 800px', null=True, upload_to=b'uploads/partners/banners', verbose_name='Baner wydarzenia'),
        ),
        migrations.AlterField(
            model_name='mediapatronage',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Szeroko\u015b\u0107 sugerowana: 1000-1600px', null=True, upload_to=b'uploads/partners/covers', verbose_name='Szeroki obraz typu cover'),
        ),
        migrations.AlterField(
            model_name='mediapatronage',
            name='small_image',
            field=models.ImageField(blank=True, help_text='Szeroko\u015b\u0107 sugerowana: 300px', null=True, upload_to=b'uploads/partners/images', verbose_name='Ma\u0142y obrazk'),
        ),
    ]
