# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-25 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20171125_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediapatronage',
            options={'verbose_name': 'Promowane wydarzenie', 'verbose_name_plural': 'Promowane wydarzenia'},
        ),
        migrations.AlterModelOptions(
            name='normalmediapatronage',
            options={'verbose_name': 'Promowany produkt', 'verbose_name_plural': 'Promowane produkty'},
        ),
    ]
