# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20171125_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapatronage',
            name='activated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aktywowano'),
        ),
        migrations.AddField(
            model_name='mediapatronage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dodano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediapatronage',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Zmieniono'),
        ),
    ]
